import type { Post, Comment, PostReport, CommentReport, User } from './types';

export const mockUsers: User[] = [
  {
    id: 'teacher-1',
    email: 'abc1234@unam.hs.kr',
    nickname: '김선생님',
    realName: '김철수',
    role: 'teacher',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'student-1',
    email: '2024001@unam.hs.kr',
    nickname: '윤서진',
    realName: '이영희',
    role: 'student',
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'student-2',
    email: '2024002@unam.hs.kr',
    nickname: '박준영',
    realName: '박민수',
    role: 'student',
    createdAt: new Date('2024-03-02'),
  },
  {
    id: 'student-3',
    email: '2024003@unam.hs.kr',
    nickname: '최하윤',
    realName: '정지훈',
    role: 'student',
    createdAt: new Date('2024-03-03'),
  },
];

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    title: '학교 축제 안내',
    content: '안녕하세요, 운암고등학교 학생 여러분!\n\n오는 5월 15일부터 17일까지 학교 축제가 개최됩니다.\n\n주요 프로그램:\n- 동아리 공연\n- 부스 운영\n- 체육대회\n\n많은 참여 부탁드립니다.',
    authorId: 'teacher-1',
    authorName: '김선생님',
    boardType: 'teacher',
    isNotice: true,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
    viewCount: 523,
    commentCount: 15,
  },
  {
    id: 'post-2',
    title: '중간고사 일정 변경 안내',
    content: '중간고사 일정이 다음과 같이 변경되었습니다.\n\n변경 전: 4월 22일 ~ 4월 26일\n변경 후: 4월 29일 ~ 5월 3일\n\n학생 여러분의 양해 부탁드립니다.',
    authorId: 'teacher-1',
    authorName: '김선생님',
    boardType: 'teacher',
    isNotice: true,
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
    viewCount: 892,
    commentCount: 32,
  },
  {
    id: 'post-3',
    title: '오늘 급식 맛있었어요!',
    content: '오늘 급식 메뉴가 제가 좋아하는 돈까스였는데 진짜 맛있었어요 ㅎㅎ\n다들 오늘 급식 어땠나요?',
    authorId: 'student-1',
    authorName: '윤서진',
    boardType: 'free',
    isNotice: false,
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-10'),
    viewCount: 45,
    commentCount: 8,
  },
  {
    id: 'post-4',
    title: '수학 문제 질문이요',
    content: '수학 교과서 156쪽 5번 문제 풀이 방법 아시는 분 계신가요?\n\n저는 이차방정식 공식을 적용해봤는데 답이 안 나와서요...',
    authorId: 'student-2',
    authorName: '박준영',
    boardType: 'subject',
    subject: '수학',
    isNotice: false,
    createdAt: new Date('2024-04-11'),
    updatedAt: new Date('2024-04-11'),
    viewCount: 67,
    commentCount: 12,
  },
  {
    id: 'post-5',
    title: '영어 단어 암기 팁 공유',
    content: '저만의 영어 단어 암기 방법을 공유할게요!\n\n1. 연상법 활용하기\n2. 예문과 함께 외우기\n3. 반복 학습 (에빙하우스 망각곡선 활용)\n\n도움이 되셨으면 좋겠습니다~',
    authorId: 'student-3',
    authorName: '최하윤',
    boardType: 'subject',
    subject: '영어',
    isNotice: false,
    createdAt: new Date('2024-04-12'),
    updatedAt: new Date('2024-04-12'),
    viewCount: 123,
    commentCount: 18,
  },
  {
    id: 'post-6',
    title: '동아리 가입 문의',
    content: '밴드 동아리 가입하고 싶은데 어떻게 해야 하나요?\n드럼 칠 줄 알아요!',
    authorId: 'student-1',
    authorName: '윤서진',
    boardType: 'free',
    isNotice: false,
    createdAt: new Date('2024-04-13'),
    updatedAt: new Date('2024-04-13'),
    viewCount: 34,
    commentCount: 5,
  },
  {
    id: 'post-7',
    title: '과학 실험 보고서 양식',
    content: '과학 실험 보고서 양식 공유합니다.\n\n1. 실험 목적\n2. 실험 준비물\n3. 실험 방법\n4. 실험 결과\n5. 결론 및 고찰\n\n참고하세요!',
    authorId: 'student-2',
    authorName: '박준영',
    boardType: 'subject',
    subject: '과학',
    isNotice: false,
    createdAt: new Date('2024-04-14'),
    updatedAt: new Date('2024-04-14'),
    viewCount: 89,
    commentCount: 7,
  },
  {
    id: 'post-8',
    title: '체육대회 반 대항전 종목 투표',
    content: '체육대회 반 대항전 종목을 정해야 합니다.\n\n1. 축구\n2. 농구\n3. 피구\n4. 줄다리기\n\n댓글로 투표해주세요!',
    authorId: 'teacher-1',
    authorName: '김선생님',
    boardType: 'teacher',
    isNotice: false,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-04-15'),
    viewCount: 156,
    commentCount: 45,
  },
];

export const mockComments: Comment[] = [
  {
    id: 'comment-1',
    postId: 'post-3',
    content: '저도요! 돈까스 진짜 맛있었어요 ㅎㅎ',
    authorId: 'student-2',
    authorName: '박준영',
    createdAt: new Date('2024-04-10T12:30:00'),
  },
  {
    id: 'comment-2',
    postId: 'post-3',
    content: '다음에 또 나왔으면 좋겠다~',
    authorId: 'student-3',
    authorName: '최하윤',
    createdAt: new Date('2024-04-10T12:35:00'),
  },
  {
    id: 'comment-3',
    postId: 'post-4',
    content: '그 문제는 인수분해를 먼저 해야 해요! 공식 적용하기 전에 식을 정리해보세요.',
    authorId: 'student-3',
    authorName: '최하윤',
    createdAt: new Date('2024-04-11T14:00:00'),
  },
  {
    id: 'comment-4',
    postId: 'post-4',
    content: '감사합니다! 인수분해하니까 풀렸어요!',
    authorId: 'student-2',
    authorName: '박준영',
    createdAt: new Date('2024-04-11T14:30:00'),
  },
  {
    id: 'comment-5',
    postId: 'post-5',
    content: '좋은 팁 감사합니다! 에빙하우스 망각곡선 처음 들어봤는데 찾아봐야겠어요.',
    authorId: 'student-1',
    authorName: '윤서진',
    createdAt: new Date('2024-04-12T16:00:00'),
  },
  {
    id: 'comment-6',
    postId: 'post-6',
    content: '밴드 동아리 부장한테 연락해보세요! 인스타 아이디 알려드릴게요.',
    authorId: 'student-2',
    authorName: '박준영',
    createdAt: new Date('2024-04-13T10:00:00'),
  },
  {
    id: 'comment-7',
    postId: 'post-8',
    content: '축구요! 축구가 제일 재밌어요',
    authorId: 'student-1',
    authorName: '윤서진',
    createdAt: new Date('2024-04-15T09:00:00'),
  },
  {
    id: 'comment-8',
    postId: 'post-8',
    content: '피구 추천합니다! 다 같이 참여할 수 있어서요',
    authorId: 'student-2',
    authorName: '박준영',
    createdAt: new Date('2024-04-15T09:15:00'),
  },
  {
    id: 'comment-9',
    postId: 'post-8',
    content: '줄다리기! 단합력 기를 수 있어요',
    authorId: 'student-3',
    authorName: '최하윤',
    createdAt: new Date('2024-04-15T09:30:00'),
  },
  {
    id: 'comment-10',
    postId: 'post-1',
    content: '축제 기대돼요!',
    authorId: 'student-1',
    authorName: '윤서진',
    createdAt: new Date('2024-04-01T10:00:00'),
  },
];

export const mockPostReports: PostReport[] = [];

export const mockCommentReports: CommentReport[] = [];
